modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "The Unlicense"

[[mods]]
modId = "resettleable_traders"
version = "${version}"
displayName = "Resettleable Traders"
authors = "donmor"
description = '''
Resettle wandering traders with beds
'''
itemIcon = "minecraft:red_bed"
updateJSONURL = "https://raw.githubusercontent.com/donmor/resettleable_traders/refs/heads/1.20.1/versions.json"
#logoFile = ""
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.resettleable_traders]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resettleable_traders]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.resettleable_traders]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[modproperties.resettleable_traders]
    catalogueImageIcon="assets/resettleable_traders/icon.png"
